### ISSUE TITLE
Docker Build wont work

### ISSUE THREAD

**Issue by foorschtbar** [skyajal/rpi4-docker#1]
Hey, nice guild! 

But, maybe there is a problem. When i disable the default bridge with `"bridge": "none"`, building images with docker compose wont work, because they seams to need the default bridge at buildtime :(

**Comment by skyajal** [comment]
Did you read the section about user-defined bridge? You should define your containers to use that bridge instead.

**Comment by skyajal** [comment]
I have updated the documentation accordingly.  Thanks for the feedback! :+1: Marking this issue as closed.

**Comment by foorschtbar** [comment]
Yes, i read that and i created the custom bridge, everything works fine but for the build i cant set a custom bridge. The build tool seams to need a bridge with the name "bridge".

**Comment by skyajal** [comment]
I use docker-compose versus dockerfile if that is what you use. Check the docker documentation on how to use a user defined bridge.
